### ISSUE TITLE
Welcome to Contribute CSBench into OpenCompass

### ISSUE THREAD

**Issue by tonysy** [csbench/csbench#2]
Hi,

Great work, we are OpenCompass Team, welcome to contribute CSBench into OpenCompass. We can provide any help if needed.

**Comment by dongguanting** [comment]
> Hi,
> 
> Great work, we are OpenCompass Team, welcome to contribute CSBench into OpenCompass. We can provide any help if needed.

Hi, we are very willing to contribute csbench to OpenCompass. What specific steps do we need to take?

**Comment by tonysy** [comment]
Hi,
Some docs may be helpful.

https://opencompass.readthedocs.io/zh-cn/latest/advanced_guides/new_dataset.html

Example:
https://github.com/open-compass/opencompass/pull/1081
https://github.com/open-compass/opencompass/pull/1032

Also welcome to contribute the bench into https://hub.opencompass.org.cn/home for more visibility

**Comment by LeonDiao0427** [comment]
Hi,
thanks for your helpful docs, we have contributed the benchmark at https://hub.opencompass.org.cn/dataset-detail/CS-Bench.
